spring:
  profiles:
    group:
      "default":
        - "dev"
      "dev":
        - "dev-kafka"
        - "dev-db"
        - "dev-eureka"
      "prod":
        - "prod-kafka"
        - "prod-db"
        - "prod-eureka"
      "docker":
        - "docker-eureka"
        - "dev-db"
        - "prod-kafka"

---
spring:
  config:
    import:
      - classpath:kafka-config.yml
      - classpath:db-config.yml
      - classpath:eureka-config.yml
  application:
    name: chat-api
---
events:
  post:
    banzzak:
      created: "post-banzzakCreated"
      deleted: "post-banzzakDeleted"
      user-joined: "post-banzzakUserJoined"
      user-left: "post-banzzakUserLeft"
  chat:
    chat-room:
      created: "chat-chatRoomCreated"
      deleted: "chat-chatRoomDeleted"
    member:
      added: "chat-memberAdded"
      left: "chat-memberLeft"


