spring:
  profiles:
    group:
      "default":
        - "dev"
      "dev":
        - "dev-kafka"
        - "dev-db"
        - "dev-eureka"
      "prod":
        - "prod-kafka"
        - "prod-db"
        - "prod-eureka"

---
spring:
  config:
    import:
      - classpath:kafka-config.yml
      - classpath:db-config.yml
      - classpath:eureka-config.yml
  application:
    name: chat-api
