
spring:
  application:
    name: chat-api
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: chat-api
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:test;
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      connection-timeout: 5000 #timeout 5sec.
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: utf-8

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
