

name: Java CI with Gradle

on:
  pull_request:


permissions:
  contents: read

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/gaaji-chat-api-service
  VERSION: ${{ github.sha }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create db-config.yml
      env:
        SECRET_CODE: ${{ secrets.DB }}
        SECRET_DIR: src/main/resources
        SECRET_FILE_NAME: db-config.yml
      run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

    - name: Create eureka-config.yml
      env:
       SECRET_CODE: ${{ secrets.EUREKA }}
       SECRET_DIR: src/main/resources
       SECRET_FILE_NAME: eureka-config.yml
      run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME
    - name: Create kafka-config.yml
      env:
        SECRET_CODE: ${{ secrets.KAFKA }}
        SECRET_DIR: src/main/resources
        SECRET_FILE_NAME: kafka-config.yml
      run: echo $SECRET_CODE | base64 --decode > $SECRET_DIR/$SECRET_FILE_NAME

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name : Set Eureka Server
      run: |
        docker pull ${{ secrets.EUREKA_DOCKER  }}
        docker run -d -p 8761:8761 ${{ secrets.EUREKA_DOCKER }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: show directory
      run: ls

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: . 			# dockerfile이 있는 위치랑 맞춰주자
        file: ./Dockerfile	# 빌드할 Dockerfile이 있는 디렉토리
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:local